# Reload the configuration automatically when changes are saved.
general.live_config_reload = true

# Import additional configuration files (ensure these paths and files exist).
general.import = [
  "C:/Users/Evrenos/AppData/Roaming/alacritty/colors.toml",
  "C:/Users/Evrenos/AppData/Roaming/alacritty/fonts.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "full"
opacity = 1.0

  [window.padding]
  x = 15
  y = 15

  [window.dimensions]
  columns = 80
  lines = 30

[scrolling]
history = 1000
multiplier = 3

[cursor]
style = "Underline"
vi_mode_style = "Underline"

[terminal]
shell = { program = "pwsh.exe", args = ["-NoExit", "-Command", "cd ~"] }
